import type { Dealer } from "@/types/dealers";

export const DEALERS: Dealer[] = [
  // === Online distributeri ===
  {
    id: "tim-komerc",
    name: "TIM KOMERC D.O.O.",
    address: "Paunova 8",
    city: "Beograd",
    email: "tim.1@mts.rs",
    website: "https://timkomerc.rs/",
    category: "online",
    coordinates: { lat: 44.8176, lng: 20.4633 },
  },
  {
    id: "zim-commerce",
    name: "ZIM COMMERCE D.O.O.",
    city: "Subotica",
    phone: "024/577-566",
    email: "zimcommercedoo@gmail.com",
    website: "https://zimcommerce.com/sr",
    category: "online",
    coordinates: { lat: 46.1003, lng: 19.6648 },
  },
  {
    id: "kliklak-racunari",
    name: "KLIKLAK RAČUNARI",
    address: "Matejevački put 36",
    city: "Niš",
    email: "info@kliklak.rs",
    website: "https://www.kliklak.rs/",
    category: "online",
    coordinates: { lat: 43.3209, lng: 21.8958 },
  },
  {
    id: "od-igle-do-lokomotive",
    name: "OD IGLE DO LOKOMOTIVE D.O.O.",
    address: "Radoja Dakića",
    city: "Niš",
    phone: "018/575-773",
    email: "office@odigledolokomotive.rs",
    category: "online",
    coordinates: { lat: 43.3167, lng: 21.8954 },
  },
  {
    id: "sualati024",
    name: "SUALATI024 D.O.O.",
    address: "Segedinski put 86",
    city: "Subotica",
    phone: "024/525-091",
    email: "sualati@gmail.com",
    website: "https://www.sualati.com/",
    category: "online",
    coordinates: { lat: 46.0964, lng: 19.6706 },
  },
  {
    id: "iskra-servis",
    name: "ISKRA SERVIS D.O.O.",
    address: "Mije Kovačevića 10",
    city: "Beograd",
    phone: "011/3290-295",
    email: "kontakt@iskraservis.pro",
    website: "https://www.iskraservis.pro/",
    category: "online",
    coordinates: { lat: 44.7942, lng: 20.4747 },
  },
  {
    id: "maxidom",
    name: "MAXIDOM D.O.O.",
    address: "Pančevački put 81",
    city: "Beograd",
    phone: "011/4240-400",
    email: "info@maxidom.rs",
    website: "https://maxidom.rs/",
    category: "online",
    coordinates: { lat: 44.8198, lng: 20.4897 },
  },
  {
    id: "mixal",
    name: "MIXAL D.O.O.",
    address: "Gandijeva 3, lokal 10",
    city: "Novi Beograd",
    phone: "011/2289-103",
    email: "info@mixalshop.rs",
    website: "https://najpovoljnijialati.rs/",
    category: "online",
    coordinates: { lat: 44.8148, lng: 20.4103 },
  },
  {
    id: "sistem-cd",
    name: "S.Z.T.K.R. SISTEM CD",
    address: "Dragoslava Srejovića 32",
    city: "Beograd",
    phone: "062/241-661",
    email: "Office@sistemcd.rs",
    website: "https://www.queencolor.rs/",
    category: "online",
    coordinates: { lat: 44.8042, lng: 20.4728 },
  },

  // === Ovlašćeni servisi ===
  {
    id: "stridon-group-service",
    name: "Stridon Group D.O.O.",
    address: "Vojislava Ilića 141g",
    city: "Beograd",
    phone: "011/4520-171",
    email: "office@stridon.rs",
    website: "https://www.prodavnicaalata.rs/",
    category: "service",
    coordinates: { lat: 44.7724, lng: 20.4989 },
  },
  {
    id: "hammercom",
    name: "Hammercom D.O.O.",
    address: "Valjevska 3",
    city: "Beograd",
    phone: "011/6543-683",
    email: "office@hammercom.co.rs",
    website: "http://www.hammercom.co.rs/",
    category: "service",
    coordinates: { lat: 44.7871, lng: 20.4568 },
  },
  {
    id: "dm-elektro",
    name: "Elektroservis DM Elektro PR",
    address: "Jaše Prodanovića 18",
    city: "Čačak",
    phone: "063/883-31060",
    email: "dmelektro032@gmail.com",
    category: "service",
    coordinates: { lat: 43.8914, lng: 20.3497 },
  },

  // === Servis van garancije ===
  {
    id: "servis-mitic",
    name: "SZR Servis Mitić",
    address: "Surčinska 103d",
    city: "Novi Beograd",
    phone: "011/2260-135",
    website: "http://www.servisalata-mitic.com",
    category: "outOfWarranty",
    coordinates: { lat: 44.7983, lng: 20.3876 },
  },
  {
    id: "stridon-group-oow",
    name: "Stridon Group D.O.O.",
    address: "Vojislava Ilića 141g",
    city: "Beograd",
    phone: "011/4520-171",
    email: "office@stridon.rs",
    website: "https://www.prodavnicaalata.rs/",
    category: "outOfWarranty",
    coordinates: { lat: 44.7724, lng: 20.4989 },
  },
];
